version: "3.7"

services:
    mdp:
        image: matiaet98/mdp:latest
        container_name: mdp
        hostname: mdp
        domainname: matinet
        privileged: true
        networks:
            matinet:
                ipv4_address: <ip>
                aliases:
                    - mdp.matinet
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
networks:
    matinet:
        external:
            name: matinet
