version: "3.7"

services:
    <hostname>:
        image: matiaet98/<hostname>:latest
        container_name: <hostname>
        hostname: <hostname>
        domainname: <domainname>
        privileged: true
        networks:
            <network>:
                ipv4_address: <ip>
                aliases:
                    - <hostname>.<domainname>
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
networks:
    <network>:
        external:
            name: <network>
